version: '3'

volumes:
  postgres_data_local: {}

services:
  django:
    container_name: pdk-django
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    ports:
      - "8132:8132"
    env_file:
      - variables.env
    command: python manage.py runserver 0.0.0.0:8132

  postgres:
    image: mdillon/postgis:9.6
    container_name: pdk-postgres
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    env_file:
      - variables.env
    ports:
    - "5432:5432"
